apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-deploy
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [student-app]}
  template:
    metadata:
      name: pod-01
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app-container
          image: kartikbhapkar07/monitor-be:latest
          
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"

