server.port=8080
spring.datasource.url=jdbc:mariadb://10.100.244.65:3306/student_db
spring.datasource.username=root
spring.datasource.password=redhat
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=student-app
